### ISSUE TITLE
Starphleet just uses the last container to complete the build

### ISSUE THREAD

**Issue by drewtron** [wballard/starphleet#180]
Instead of the most recent check-in.

I had a npm rebuild take a long time for some reason(big surprise), and another later check-in had completed first.  The old version got deployed over the newer version of code just because it built slower.

**Comment by bhudgens** [comment]
This was resolved in this set of changes:

https://github.com/wballard/starphleet/commit/d29c29851abf1d98e0ee56d17dc15470bdc09257
